### PR TITLE
AustVStatCalc

### PR DESCRIPTION
**Pull request by AustinV9121**
HW1. Fixed table oversizing on multiple file selections, new file explorer 'choose file' option, new standard statistics calculations outputs

### CODE REVIEW

**Review by jeremydaily — CHANGES_REQUESTED** [review]
It looks like you deleted all the files. Please revert the original files and use the original filename.

**Review by jeremydaily — CHANGES_REQUESTED** [review]
Leave 02_add_histograms_and_pdfs.py in the directory and remove statCalcAustinV.py

**Review by jeremydaily — CHANGES_REQUESTED** [review]
Still needs 6. Add a dialog box to open and load any Comma Separated Values table.

Files look better now.

**Comment by AustinV9121** [comment]
That's what the choose file button is.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jeremydaily** [comment]
Don't use the Tk library. Stick with QT. They are competing and it crashed the program.

**Review by jeremydaily — COMMENTED** [review]
Looks good. Thanks.

**Pull request closed without merging**
